log_format day3 '$time_iso8601 '
                'request="$request" '
                'status=$status '
                'upstream_addr=$upstream_addr '
                'request_time=$request_time '
                'upstream_response_time=$upstream_response_time';

access_log /var/log/nginx/day3_access.log day3;
